export const MOCK_JOBS = [
  {
    id: 1,
    title: "Senior React Developer",
    company: "Meta",
    location: "New York, NY",
  },
  {
    id: 2,
    title: "Frontend Engineer",
    company: "Apple",
    location: "Cupertino, CA",
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "Netflix",
    location: "Remote",
  },
  {
    id: 4,
    title: "Junior Vue Developer",
    company: "Google",
    location: "Austin, TX",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "Amazon",
    location: "Seattle, WA",
  },
  {
    id: 6,
    title: "Node.js Backend Engineer",
    company: "Microsoft",
    location: "Redmond, WA",
  },
  {
    id: 7,
    title: "React Native Developer",
    company: "Tesla",
    location: "Palo Alto, CA",
  },
  {
    id: 8,
    title: "Lead Backend Engineer (Python)",
    company: "Spotify",
    location: "New York, NY",
  },
  {
    id: 9,
    title: "DevOps Engineer",
    company: "Salesforce",
    location: "San Francisco, CA",
  },
  { id: 10, title: "Data Scientist", company: "Twitter", location: "Remote" },
  {
    id: 11,
    title: "Mid-Level Android Developer",
    company: "Uber",
    location: "San Francisco, CA",
  },
  {
    id: 12,
    title: "Senior Product Manager",
    company: "Adobe",
    location: "San Jose, CA",
  },
  {
    id: 13,
    title: "Cloud Solutions Architect",
    company: "Oracle",
    location: "Austin, TX",
  },
  {
    id: 14,
    title: "Junior Frontend Developer",
    company: "Shopify",
    location: "Toronto, Canada",
  },
  {
    id: 15,
    title: "Machine Learning Engineer",
    company: "NVIDIA",
    location: "Santa Clara, CA",
  },
  {
    id: 16,
    title: "Site Reliability Engineer",
    company: "Stripe",
    location: "Remote",
  },
  {
    id: 17,
    title: "Senior iOS Developer",
    company: "Lyft",
    location: "New York, NY",
  },
  {
    id: 18,
    title: "Full Stack Engineer (MERN)",
    company: "Airbnb",
    location: "San Francisco, CA",
  },
  {
    id: 19,
    title: "Principal Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
  },
  {
    id: 20,
    title: "UX Researcher",
    company: "Meta",
    location: "Menlo Park, CA",
  },
  {
    id: 21,
    title: "Backend Engineer (Go)",
    company: "Netflix",
    location: "Los Gatos, CA",
  },
  {
    id: 22,
    title: "Angular Developer",
    company: "Microsoft",
    location: "Remote",
  },
  {
    id: 23,
    title: "QA Automation Engineer",
    company: "Amazon",
    location: "Arlington, VA",
  },
  { id: 24, title: "Data Analyst", company: "Tesla", location: "Austin, TX" },
  {
    id: 25,
    title: "Lead Frontend Engineer",
    company: "Apple",
    location: "Cupertino, CA",
  },
  {
    id: 26,
    title: "Senior Java Developer",
    company: "Intel",
    location: "Hillsboro, OR",
  },
  { id: 27, title: "Product Designer", company: "Slack", location: "Remote" },
  {
    id: 28,
    title: "Cybersecurity Analyst",
    company: "IBM",
    location: "Armonk, NY",
  },
  {
    id: 29,
    title: "Junior DevOps Engineer",
    company: "Atlassian",
    location: "Sydney, Australia",
  },
  {
    id: 30,
    title: "Ruby on Rails Developer",
    company: "GitHub",
    location: "Remote",
  },
  {
    id: 31,
    title: "AI Research Scientist",
    company: "OpenAI",
    location: "San Francisco, CA",
  },
  {
    id: 32,
    title: "Engineering Manager",
    company: "Spotify",
    location: "Stockholm, Sweden",
  },
  {
    id: 33,
    title: "Mid-Level Full Stack Developer",
    company: "HubSpot",
    location: "Cambridge, MA",
  },
  {
    id: 34,
    title: "Senior UI Engineer",
    company: "Twilio",
    location: "Remote",
  },
  {
    id: 35,
    title: "Flutter Developer",
    company: "Google",
    location: "London, UK",
  },
  {
    id: 36,
    title: "Database Administrator",
    company: "Oracle",
    location: "Redwood City, CA",
  },
  {
    id: 37,
    title: "Technical Program Manager",
    company: "Amazon Web Services",
    location: "Seattle, WA",
  },
  {
    id: 38,
    title: "Software Engineer, C++",
    company: "Microsoft",
    location: "Redmond, WA",
  },
  {
    id: 39,
    title: "Growth Product Manager",
    company: "Pinterest",
    location: "San Francisco, CA",
  },
  {
    id: 40,
    title: "Systems Engineer",
    company: "Cisco",
    location: "San Jose, CA",
  },
  {
    id: 41,
    title: "Senior Data Engineer",
    company: "Netflix",
    location: "Remote",
  },
  {
    id: 42,
    title: "React Developer",
    company: "Square",
    location: "New York, NY",
  },
  {
    id: 43,
    title: "Marketing Technology Manager",
    company: "Salesforce",
    location: "Indianapolis, IN",
  },
  {
    id: 44,
    title: "Cloud Security Engineer",
    company: "Palo Alto Networks",
    location: "Santa Clara, CA",
  },
  { id: 45, title: "Lead Designer", company: "Airbnb", location: "Remote" },
  {
    id: 46,
    title: "Senior Backend Engineer (Java)",
    company: "Amazon",
    location: "Vancouver, Canada",
  },
  {
    id: 47,
    title: "Junior Data Scientist",
    company: "Meta",
    location: "Seattle, WA",
  },
  {
    id: 48,
    title: "IT Support Specialist",
    company: "Apple",
    location: "Austin, TX",
  },
  {
    id: 49,
    title: "Blockchain Developer",
    company: "Coinbase",
    location: "Remote",
  },
  {
    id: 50,
    title: "Senior SRE",
    company: "Google",
    location: "Zurich, Switzerland",
  },
  {
    id: 51,
    title: "Frontend Engineer (Vue.js)",
    company: "GitLab",
    location: "Remote",
  },
  {
    id: 52,
    title: "Python Automation Engineer",
    company: "Tesla",
    location: "Fremont, CA",
  },
  {
    id: 53,
    title: "AR/VR Software Engineer",
    company: "Meta",
    location: "Redmond, WA",
  },
  {
    id: 54,
    title: "Technical Writer",
    company: "Stripe",
    location: "Dublin, Ireland",
  },
  {
    id: 55,
    title: "Solutions Engineer",
    company: "Twilio",
    location: "San Francisco, CA",
  },
  { id: 56, title: "Android Engineer", company: "Spotify", location: "Remote" },
  {
    id: 57,
    title: "Data Warehouse Engineer",
    company: "Snowflake",
    location: "San Mateo, CA",
  },
  {
    id: 58,
    title: "Head of Engineering",
    company: "Notion",
    location: "San Francisco, CA",
  },
  {
    id: 59,
    title: "Embedded Software Engineer",
    company: "Apple",
    location: "San Diego, CA",
  },
  {
    id: 60,
    title: "Senior Cloud Engineer (AWS)",
    company: "Netflix",
    location: "Los Gatos, CA",
  },
  {
    id: 61,
    title: "Mid-Level React Developer",
    company: "Vercel",
    location: "Remote",
  },
  {
    id: 62,
    title: "Information Security Officer",
    company: "Microsoft",
    location: "Reston, VA",
  },
  {
    id: 63,
    title: "Full Stack Developer (PHP)",
    company: "Automattic",
    location: "Remote",
  },
  {
    id: 64,
    title: "Machine Learning Ops (MLOps) Engineer",
    company: "Databricks",
    location: "San Francisco, CA",
  },
  {
    id: 65,
    title: "Junior Product Designer",
    company: "Figma",
    location: "New York, NY",
  },
  { id: 66, title: "Mobile QA Engineer", company: "Uber", location: "Remote" },
  {
    id: 67,
    title: "Principal Cloud Architect",
    company: "Google Cloud",
    location: "Sunnyvale, CA",
  },
  {
    id: 68,
    title: "Senior Golang Developer",
    company: "Dropbox",
    location: "San Francisco, CA",
  },
  {
    id: 69,
    title: "Director of Product Management",
    company: "Shopify",
    location: "Remote",
  },
  {
    id: 70,
    title: "Rust Engineer",
    company: "Mozilla",
    location: "Mountain View, CA",
  },
  {
    id: 71,
    title: "Business Intelligence Analyst",
    company: "Tableau",
    location: "Seattle, WA",
  },
  {
    id: 72,
    title: "Scrum Master",
    company: "Salesforce",
    location: "Chicago, IL",
  },
  {
    id: 73,
    title: "Software Development Engineer in Test (SDET)",
    company: "Amazon",
    location: "Remote",
  },
  {
    id: 74,
    title: "Senior UX Designer",
    company: "Adobe",
    location: "New York, NY",
  },
  {
    id: 75,
    title: "Game Developer (Unity)",
    company: "Electronic Arts",
    location: "Austin, TX",
  },
  {
    id: 76,
    title: "Kubernetes Engineer",
    company: "Red Hat",
    location: "Raleigh, NC",
  },
  {
    id: 77,
    title: "Firmware Engineer",
    company: "Intel",
    location: "Chandler, AZ",
  },
  {
    id: 78,
    title: "Senior Mobile Engineer (iOS)",
    company: "Airbnb",
    location: "Portland, OR",
  },
  {
    id: 79,
    title: "Data Privacy Manager",
    company: "Meta",
    location: "Washington, D.C.",
  },
  {
    id: 80,
    title: "Typescript Developer",
    company: "Microsoft",
    location: "Bellevue, WA",
  },
  {
    id: 81,
    title: "Junior Backend Engineer (Node.js)",
    company: "Slack",
    location: "Denver, CO",
  },
  {
    id: 82,
    title: "Lead Data Scientist",
    company: "Netflix",
    location: "Los Angeles, CA",
  },
  {
    id: 83,
    title: "Frontend Platform Engineer",
    company: "Spotify",
    location: "Boston, MA",
  },
  {
    id: 84,
    title: "Cloud Engineer (Azure)",
    company: "Microsoft",
    location: "Remote",
  },
  {
    id: 85,
    title: "Senior Software Engineer, Security",
    company: "Apple",
    location: "Cupertino, CA",
  },
  {
    id: 86,
    title: "Full Stack Python/Django Developer",
    company: "Instagram",
    location: "Remote",
  },
  {
    id: 87,
    title: "Web Accessibility Specialist",
    company: "Google",
    location: "Mountain View, CA",
  },
  {
    id: 88,
    title: "Analytics Engineer",
    company: "dbt Labs",
    location: "Remote",
  },
  {
    id: 89,
    title: "Senior Elixir Developer",
    company: "Discord",
    location: "San Francisco, CA",
  },
  {
    id: 90,
    title: "Developer Advocate",
    company: "HashiCorp",
    location: "Remote",
  },
  {
    id: 91,
    title: "Quantitative Analyst",
    company: "Goldman Sachs",
    location: "New York, NY",
  },
  {
    id: 92,
    title: "Design Systems Lead",
    company: "Atlassian",
    location: "Austin, TX",
  },
  {
    id: 93,
    title: "Senior Network Engineer",
    company: "Amazon Web Services",
    location: "Herndon, VA",
  },
  {
    id: 94,
    title: "Product Marketing Manager",
    company: "HubSpot",
    location: "Remote",
  },
  {
    id: 95,
    title: "C# / .NET Developer",
    company: "Microsoft",
    location: "Redmond, WA",
  },
  {
    id: 96,
    title: "Haskell Engineer",
    company: "Meta",
    location: "London, UK",
  },
  {
    id: 97,
    title: "Mid-Level DevOps Engineer",
    company: "Tesla",
    location: "Reno, NV",
  },
  { id: 98, title: "Cloud Economist", company: "Oracle", location: "Remote" },
  {
    id: 99,
    title: "Senior Android Engineer",
    company: "Google",
    location: "New York, NY",
  },
  {
    id: 100,
    title: "Head of Developer Relations",
    company: "Vercel",
    location: "Remote",
  },
];
